[package]
name = "sprint0"
version = "0.1.0"
edition = "2024"

[[example]]
name = "a"
path = "examples/a.rs"

[[example]]
name = "b"
path = "examples/b.rs"

[[example]]
name = "c"
path = "examples/c.rs"

[[example]]
name = "d"
path = "examples/d.rs"

[[example]]
name = "e"
path = "examples/e.rs"